#include "CGlobals.h"

#define DEFINE_ENCODING_GETTER(name, constant) \
    OnigEncoding get_onig_##name() { return constant; }

#define DEFINE_SYNTAX_GETTER(name, constant) \
    OnigSyntaxType* get_onig_##name() { return constant; }

DEFINE_ENCODING_GETTER(ascii, ONIG_ENCODING_ASCII)
DEFINE_ENCODING_GETTER(iso8859_1, ONIG_ENCODING_ISO_8859_1)
DEFINE_ENCODING_GETTER(iso8859_2, ONIG_ENCODING_ISO_8859_2)
DEFINE_ENCODING_GETTER(iso8859_3, ONIG_ENCODING_ISO_8859_3)
DEFINE_ENCODING_GETTER(iso8859_4, ONIG_ENCODING_ISO_8859_4)
DEFINE_ENCODING_GETTER(iso8859_5, ONIG_ENCODING_ISO_8859_5)
DEFINE_ENCODING_GETTER(iso8859_6, ONIG_ENCODING_ISO_8859_6)
DEFINE_ENCODING_GETTER(iso8859_7, ONIG_ENCODING_ISO_8859_7)
DEFINE_ENCODING_GETTER(iso8859_8, ONIG_ENCODING_ISO_8859_8)
DEFINE_ENCODING_GETTER(iso8859_9, ONIG_ENCODING_ISO_8859_9)
DEFINE_ENCODING_GETTER(iso8859_10, ONIG_ENCODING_ISO_8859_10)
DEFINE_ENCODING_GETTER(iso8859_11, ONIG_ENCODING_ISO_8859_11)
DEFINE_ENCODING_GETTER(iso8859_13, ONIG_ENCODING_ISO_8859_13)
DEFINE_ENCODING_GETTER(iso8859_14, ONIG_ENCODING_ISO_8859_14)
DEFINE_ENCODING_GETTER(iso8859_15, ONIG_ENCODING_ISO_8859_15)
DEFINE_ENCODING_GETTER(iso8859_16, ONIG_ENCODING_ISO_8859_16)
DEFINE_ENCODING_GETTER(utf8, ONIG_ENCODING_UTF8)
DEFINE_ENCODING_GETTER(utf16be, ONIG_ENCODING_UTF16_BE)
DEFINE_ENCODING_GETTER(utf16le, ONIG_ENCODING_UTF16_LE)
DEFINE_ENCODING_GETTER(utf32be, ONIG_ENCODING_UTF32_BE)
DEFINE_ENCODING_GETTER(utf32le, ONIG_ENCODING_UTF32_LE)
DEFINE_ENCODING_GETTER(eucjp, ONIG_ENCODING_EUC_JP)
DEFINE_ENCODING_GETTER(euctw, ONIG_ENCODING_EUC_TW)
DEFINE_ENCODING_GETTER(euckr, ONIG_ENCODING_EUC_KR)
DEFINE_ENCODING_GETTER(euccn, ONIG_ENCODING_EUC_CN)
DEFINE_ENCODING_GETTER(sjis, ONIG_ENCODING_SJIS)
DEFINE_ENCODING_GETTER(koi8r, ONIG_ENCODING_KOI8_R)
DEFINE_ENCODING_GETTER(cp1251, ONIG_ENCODING_CP1251)
DEFINE_ENCODING_GETTER(big5, ONIG_ENCODING_BIG5)
DEFINE_ENCODING_GETTER(gb18030, ONIG_ENCODING_GB18030)

DEFINE_SYNTAX_GETTER(asis, ONIG_SYNTAX_ASIS)
DEFINE_SYNTAX_GETTER(posix_basic, ONIG_SYNTAX_POSIX_BASIC)
DEFINE_SYNTAX_GETTER(posix_extended, ONIG_SYNTAX_POSIX_EXTENDED)
DEFINE_SYNTAX_GETTER(emacs, ONIG_SYNTAX_EMACS)
DEFINE_SYNTAX_GETTER(grep, ONIG_SYNTAX_GREP)
DEFINE_SYNTAX_GETTER(gnu_regex, ONIG_SYNTAX_GNU_REGEX)
DEFINE_SYNTAX_GETTER(java, ONIG_SYNTAX_JAVA)
DEFINE_SYNTAX_GETTER(perl, ONIG_SYNTAX_PERL)
DEFINE_SYNTAX_GETTER(perl_ng, ONIG_SYNTAX_PERL_NG)
DEFINE_SYNTAX_GETTER(ruby, ONIG_SYNTAX_RUBY)
DEFINE_SYNTAX_GETTER(oniguruma, ONIG_SYNTAX_ONIGURUMA)
DEFINE_SYNTAX_GETTER(default_syntax, ONIG_SYNTAX_DEFAULT)

#undef DEFINE_ENCODING_GETTER
#undef DEFINE_SYNTAX_GETTER
